id: AD2E8E362
title: Prayer of Truthful Words to Pacify the Fear of War
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:46:55.032471
  last_modified_at: 2022-03-01 01:46:55.032475
