id: AD2E8E362
title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha Thangtong
  Gyalpo's Lifetime as Bhikṣu Padma Karpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:46:55.043440
  last_modified_at: 2022-03-01 01:46:55.043443
