id: AD2E8E362
title: 'Far-Reaching Benefit of Beings, Extensive as the Sky: Visualization and Mantra
  Recitation of the Great Compassionate One'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:46:55.027428
  last_modified_at: 2022-03-01 01:46:55.027435
