id: AD2E8E362
title: Prayer for Dispelling Famine
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:46:55.029400
  last_modified_at: 2022-03-01 01:46:55.029405
