id: AD2E8E362
title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily Practice
  Uniting the Short Lineages of Amitāyus and Hayagrīva'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:46:55.044845
  last_modified_at: 2022-03-01 01:46:55.044848
