id: AD2E8E362
title: Prayer to Thangtong Gyalpo
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:46:55.034437
  last_modified_at: 2022-03-01 01:46:55.034440
