id: AD2E8E362
title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
  that Unites the Oral, Treasure and Visionary Teachings'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:46:55.035729
  last_modified_at: 2022-03-01 01:46:55.035731
