id: AD2E8E362
title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the Fear
  of Disease'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:46:55.042119
  last_modified_at: 2022-03-01 01:46:55.042122
